// 05-nhost-svelte-tutorial/src/routes/profile/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { auth } from "$lib/nhost/auth";
  
  // Redirect if not authenticated
  $effect(() => {
    if (!$auth.isLoading && !$auth.isAuthenticated) {
      void goto("/");
    }
  });
  </script>
  
  {#if $auth.isLoading}
    <div class="loading-container">
      <div class="loading-content">
        <div class="spinner"></div>
        <span class="loading-text">Loading...</span>
      </div>
    </div>
  {:else if $auth.isAuthenticated}
    <div class="container">
      <header class="page-header">
        <h1 class="page-title">Your Profile</h1>
      </header>
  
      <div class="form-card">
        <h3 class="form-title">User Information</h3>
        <div class="form-fields">
          <div class="field-group">
            <strong>Display Name:</strong> {$auth.user?.displayName || "Not set"}
          </div>
          <div class="field-group">
            <strong>Email:</strong> {$auth.user?.email || "Not available"}
          </div>
          <div class="field-group">
            <strong>User ID:</strong> {$auth.user?.id || "Not available"}
          </div>
          <div class="field-group">
            <strong>Roles:</strong> {$auth.user?.roles?.join(", ") || "None"}
          </div>
          <div class="field-group">
            <strong>Email Verified:</strong>
            <span class={$auth.user?.emailVerified ? 'email-verified' : 'email-unverified'}>
              {$auth.user?.emailVerified ? "✓ Yes" : "✗ No"}
            </span>
          </div>
        </div>
      </div>
  
      <div class="form-card">
        <h3 class="form-title">Session Information</h3>
        <div class="description">
          <pre class="session-display">{JSON.stringify($auth.session, null, 2)}</pre>
        </div>
      </div>
    </div>
  {:else}
    <div class="container">
      <div class="page-center">
        <h2>Access Denied</h2>
        <p>You must be signed in to view this page.</p>
      </div>
    </div>
  {/if}

// 06-nhost-reactnative-tutorial/app/profile.tsx
import { ScrollView, Text, View } from "react-native";
import ProtectedScreen from "./components/ProtectedScreen";
import { useAuth } from "./lib/nhost/AuthProvider";
import { commonStyles, profileStyles } from "./styles/commonStyles";

export default function Profile() {
  const { user, session } = useAuth();

  return (
    <ProtectedScreen>
      <ScrollView
        style={commonStyles.container}
        contentContainerStyle={commonStyles.contentContainer}
      >
        <Text style={commonStyles.title}>Your Profile</Text>

        <View style={commonStyles.card}>
          <Text style={commonStyles.cardTitle}>User Information</Text>

          <View style={profileStyles.profileItem}>
            <Text style={commonStyles.labelText}>Display Name:</Text>
            <Text style={commonStyles.valueText}>
              {user?.displayName || "Not set"}
            </Text>
          </View>

          <View style={profileStyles.profileItem}>
            <Text style={commonStyles.labelText}>Email:</Text>
            <Text style={commonStyles.valueText}>
              {user?.email || "Not available"}
            </Text>
          </View>

          <View style={profileStyles.profileItem}>
            <Text style={commonStyles.labelText}>User ID:</Text>
            <Text
              style={commonStyles.valueText}
              numberOfLines={1}
              ellipsizeMode="middle"
            >
              {user?.id || "Not available"}
            </Text>
          </View>

          <View style={profileStyles.profileItem}>
            <Text style={commonStyles.labelText}>Roles:</Text>
            <Text style={commonStyles.valueText}>
              {user?.roles?.join(", ") || "None"}
            </Text>
          </View>

          <View
            style={[profileStyles.profileItem, profileStyles.profileItemLast]}
          >
            <Text style={commonStyles.labelText}>Email Verified:</Text>
            <Text
              style={[
                commonStyles.valueText,
                user?.emailVerified
                  ? commonStyles.successText
                  : commonStyles.errorText,
              ]}
            >
              {user?.emailVerified ? "✓ Yes" : "✗ No"}
            </Text>
          </View>
        </View>

        <View style={commonStyles.card}>
          <Text style={commonStyles.cardTitle}>Session Information</Text>
          <View style={commonStyles.sessionInfo}>
            <Text style={commonStyles.sessionValue}>
              {JSON.stringify(session, null, 2)}
            </Text>
          </View>
        </View>
      </ScrollView>
    </ProtectedScreen>
  );
}
