// 04-nhost-vue-tutorial/src/views/Verify.vue
<template>
  <div>
    <h1>Email Verification</h1>

    <div class="page-center">
      <div v-if="status === 'verifying'">
        <p class="margin-bottom">Verifying your email...</p>
        <div class="spinner-verify" />
      </div>

      <div v-else-if="status === 'success'">
        <p class="verification-status">
          ✓ Successfully verified!
        </p>
        <p>You'll be redirected to your profile page shortly...</p>
      </div>

      <div v-else-if="status === 'error'">
        <p class="verification-status error">
          Verification failed
        </p>
        <p class="margin-bottom">{{ error }}</p>

        <div v-if="Object.keys(urlParams).length > 0" class="debug-panel">
          <p class="debug-title">
            URL Parameters:
          </p>
          <div
            v-for="[key, value] in Object.entries(urlParams)"
            :key="key"
            class="debug-item"
          >
            <span class="debug-key">
              {{ key }}:
            </span>
            <span class="debug-value">{{ value }}</span>
          </div>
        </div>

        <button
          type="button"
          @click="router.push('/signin')"
          class="auth-button secondary"
        >
          Back to Sign In
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useAuth } from "../lib/nhost/auth";

const PKCE_VERIFIER_KEY = "nhost_pkce_verifier";

function consumePKCEVerifier(): string | null {
  const verifier = localStorage.getItem(PKCE_VERIFIER_KEY);
  if (verifier) {
    localStorage.removeItem(PKCE_VERIFIER_KEY);
  }
  return verifier;
}

const route = useRoute();
const router = useRouter();
const { nhost } = useAuth();

const status = ref<"verifying" | "success" | "error">("verifying");
const error = ref<string>("");
const urlParams = ref<Record<string, string>>({});

let isMounted = true;

onMounted(() => {
  const params = new URLSearchParams(route.fullPath.split("?")[1] || "");
  const code = params.get("code");

  if (!code) {
    const allParams: Record<string, string> = {};
    params.forEach((value, key) => {
      allParams[key] = value;
    });
    urlParams.value = allParams;

    status.value = "error";
    error.value = "No authorization code found in URL";
    return;
  }

  exchangeCode(code);
});

onUnmounted(() => {
  isMounted = false;
});

async function exchangeCode(code: string): Promise<void> {
  try {
    // Small delay to ensure component is fully mounted
    await new Promise((resolve) => setTimeout(resolve, 500));

    if (!isMounted) return;

    const codeVerifier = consumePKCEVerifier();
    if (!codeVerifier) {
      status.value = "error";
      error.value =
        "No PKCE verifier found. The sign-in must be initiated from the same browser tab.";
      return;
    }

    await nhost.auth.tokenExchange({ code, codeVerifier });

    if (!isMounted) return;

    status.value = "success";

    setTimeout(() => {
      if (isMounted) router.push("/profile");
    }, 1500);
  } catch (err) {
    const message = (err as Error).message || "Unknown error";
    if (!isMounted) return;

    status.value = "error";
    error.value = `An error occurred during verification: ${message}`;
  }
}
</script>

// 02-nhost-react-tutorial/src/pages/Verify.tsx
import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../lib/nhost/useAuth";

const PKCE_VERIFIER_KEY = "nhost_pkce_verifier";

function consumePKCEVerifier(): string | null {
  const verifier = localStorage.getItem(PKCE_VERIFIER_KEY);
  if (verifier) {
    localStorage.removeItem(PKCE_VERIFIER_KEY);
  }
  return verifier;
}

export default function Verify() {
  const location = useLocation();
  const navigate = useNavigate();

  const [status, setStatus] = useState<"verifying" | "success" | "error">(() => {
    const params = new URLSearchParams(location.search);
    return params.get("code") ? "verifying" : "error";
  });
  const [error, setError] = useState<string>(() => {
    const params = new URLSearchParams(location.search);
    return params.get("code") ? "" : "No authorization code found in URL";
  });
  const [urlParams] = useState<Record<string, string>>(() => {
    const params = new URLSearchParams(location.search);
    if (params.get("code")) return {};
    const allParams: Record<string, string> = {};
    params.forEach((value, key) => { allParams[key] = value; });
    return allParams;
  });

  const { nhost } = useAuth();

  useEffect(() => {
    const params = new URLSearchParams(location.search);
    const code = params.get("code");

    if (!code) return;

    const authCode = code;
    let isMounted = true;

    async function exchangeCode(): Promise<void> {
      try {
        // Small delay to ensure component is fully mounted
        await new Promise((resolve) => setTimeout(resolve, 500));

        if (!isMounted) return;

        const codeVerifier = consumePKCEVerifier();
        if (!codeVerifier) {
          setStatus("error");
          setError(
            "No PKCE verifier found. The sign-in must be initiated from the same browser tab.",
          );
          return;
        }

        await nhost.auth.tokenExchange({ code: authCode, codeVerifier });

        if (!isMounted) return;

        setStatus("success");

        setTimeout(() => {
          if (isMounted) navigate("/profile");
        }, 1500);
      } catch (err) {
        const message = (err as Error).message || "Unknown error";
        if (!isMounted) return;

        setStatus("error");
        setError(`An error occurred during verification: ${message}`);
      }
    }

    exchangeCode();

    return () => {
      isMounted = false;
    };
  }, [location.search, navigate, nhost.auth]);

  return (
    <div>
      <h1>Email Verification</h1>

      <div className="page-center">
        {status === "verifying" && (
          <div>
            <p className="margin-bottom">Verifying your email...</p>
            <div className="spinner-verify" />
            <style>{`
              @keyframes spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
              }
            `}</style>
          </div>
        )}

        {status === "success" && (
          <div>
            <p className="verification-status">✓ Successfully verified!</p>
            <p>You'll be redirected to your profile page shortly...</p>
          </div>
        )}

        {status === "error" && (
          <div>
            <p className="verification-status error">Verification failed</p>
            <p className="margin-bottom">{error}</p>

            {Object.keys(urlParams).length > 0 && (
              <div className="debug-panel">
                <p className="debug-title">URL Parameters:</p>
                {Object.entries(urlParams).map(([key, value]) => (
                  <div key={key} className="debug-item">
                    <span className="debug-key">{key}:</span>{" "}
                    <span className="debug-value">{value}</span>
                  </div>
                ))}
              </div>
            )}

            <button
              type="button"
              onClick={() => navigate("/signin")}
              className="auth-button secondary"
            >
              Back to Sign In
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
